#Classic :   capture will be beyond and move horizontal classic move
#square := normal board, relay
#pod :  no fruit bearing,  no capture plus

name: classic_square_pod
display: Classic Square Pod
version: "c2d-0.001"
status: OK
tier: 1
options:
  - easy
  - medium
  - hard

doc: docs/text/rules_classic_square_pod.txt

rule:
  algo: "classic"
  json: "engine/rules/json/pal.json"
  mode: "square"
  tier: "pod"
  players:
    min: 2
    max: 2

easy:
  base:
    nseeds: 4
    npits: 5
  time:
    max: 200
  clock:
    enabled: false

medium:
  base:
    nseeds: 6
    npits: 7
  time:
    max: 90
  clock:
    enabled: false

hard:
  base:
    nseeds: 12
    npits: 11
  time:
    max: 60
  clock:
    enabled: true
    min: 40
