#Classic :   capture will be beyond and move horizontal classic move
#square := normal board, relay
#pro :  enable fruit bearing and capture plus

name: classic_square_pro
display: Classic Square Pro
version: "c2o-0.001"
status: OK
tier: 1
options:
  - easy
  - medium
  - hard

doc: docs/text/rules_classic_square_pro.txt

rule:
  algo: "classic"
  json: "engine/rules/json/pal.json"
  mode: "square"
  tier: "pro"

easy:
  base:
    nseeds: 4
    npits: 5
  fruit:
    count: 3
  time:
    max: 200
  clock:
    enabled: false

medium:
  base:
    nseeds: 6
    npits: 7
  fruit:
    count: 4
  time:
    max: 90
  clock:
    enabled: false

hard:
  base:
    nseeds: 12
    npits: 11
  fruit:
    count: 6
  time:
    max: 60
  clock:
    enabled: true
    min: 40
