#Classic :   capture will be beyond and move horizontal classic move
#One : normal board , no relay
#pod :  no fruit bearing,  no capture plus
name: classic_one_pod
display: Classic One Pod
version: "cod-0.001"
status: OK
tier: 1
options:
  - easy
  - medium
  - hard

doc: docs/text/rules_classic_one_pod.txt

rule:
  algo: "classic"
  json: "engine/rules/json/pal.json"
  tier: pod
  mode: one

easy:
  level: "beginner"
  base:
    nseeds: 4
    npits: 5
  time:
    max: 200
  clock:
    enabled: false

medium:
  level: "intermediate"
  base:
    nseeds: 6
    npits: 7
  time:
    max: 90
  clock:
    enabled: false

hard:
  level: "expert"
  base:
    nseeds: 12
    npits: 11
  time:
    max: 60
  clock:
    enabled: true
    min: 40
