#Classic :   capture will be beyond and move horizontal classic move
#power := kings board, relay
#pro :  enable fruit bearing and capture plus

name: classic_power_pro
display: Classic Power Pro
version: "cwo-0.001"
status: OK
tier: 1
options:
  - easy
  - medium
  - hard

doc: docs/text/rules_classic_power_pro.txt

rule:
  algo: "classic"
  json: "engine/rules/json/pal.json"
  mode: "power"
  tier: "pro"
  players:
    min: 2
    max: 2

easy:
  base:
    nseeds: 4
    npits: 5
  fruit: 3
  time:
    max: 200
  clock:
    enabled: false
  specialPits: [2, 7]

medium:
  base:
    nseeds: 6
    npits: 7
  fruit: 4
  time:
    max: 90
  clock:
    enabled: false
  specialPits: [3, 10]

hard:
  base:
    nseeds: 10
    npits: 11
  fruit: 6
  time:
    max: 60
  clock:
    enabled: true
    min: 40
  specialPits: [5, 16]
