#Classic :   capture will be beyond and move horizontal classic move
#plus := kings board, no relay
#pod :  no fruit bearing,  no capture plus

name: classic_plus_pod
display: Classic plus Pod
version: "cpd-0.001"
status: OK
tier: 1
options:
  - easy
  - medium
  - hard

doc: docs/text/rules_classic_plus_pod.txt

rule:
  algo: "classic"
  json: "engine/rules/json/pal.json"
  mode: "plus"
  tier: "pod"

easy:
  base:
    nseeds: 4
    npits: 5
  time:
    max: 200
  clock:
    enabled: false
  specialPits: [2, 7]

medium:
  base:
    nseeds: 6
    npits: 7
  time:
    max: 90
  clock:
    enabled: false
  specialPits: [3, 10]

hard:
  base:
    nseeds: 10
    npits: 11
  time:
    max: 90
  clock:
    enabled: true
    min: 60
  specialPits: [5, 16]
